[package]
name = "logos-iter"
version = "0.1.0"
edition = "2018"
authors = ["Arsenii Lyashenko <arsenylyashenko.3@gmail.com>"]
license = "MIT OR Apache-2.0"
include = ["Cargo.toml", "LICENSE-*.md", "src/**/*"]

[dependencies]
logos = "0.12.0"
